// Svelte/first_step/src/Modal.svelte
<script>
    export let showModal;
    export let isPremium;


</script>

{#if showModal}
<div class="backdrop" on:click|self>
 <div class="modal" class:isPremium = {isPremium}>
<slot>

</slot>
 </div>
</div>
    {/if}

<style>

    .backdrop{
        width: 100%;
        height: 100%;
        background: rgba(0,0,0,0.8);
        position: fixed;
        top: 0;
        left: 0;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .modal{
        background: white;
        padding: 20px;
        border-radius: 10px;
        max-width: 400px;
        margin: 10% auto;
        text-align: center;
        z-index: 2;
    }
    .isPremium{
        background: white;
        padding: 20px;
        border-radius: 10px;
        border: gold solid 2px;
        max-width: 400px;
        margin: 10% auto;
        text-align: center;
        transform: scale(1.2);
        color: gold;
    }
</style>

// Vue/vueTest/vueTest/src/components/Modal.vue

<template>
  <div class="backdrop" @click.self="closeModal">
    <div class="modal" :class="{sale:theme === 'sale'}">

      <div class="actions">
        <slot name="links">

        </slot>
      </div>
    </div>
  </div>
</template>
<script>
export default {
props:['theme'],
methods:{
  closeModal(){
    this.$emit('close');
  },
  closeModal2(){
    this.$emit('close2');
  }
},
}

</script>

<style>
.modal {
  width: 400px;
  padding: 20px;
  margin: 200px auto;
  background: white;
  border-radius: 10px;
}
.backdrop {
  top: 0;
  position: fixed;
  background: rgba(0,0,0,0.5);
  width: 100%;
  height: 100%;
}
.modal h1 {
  color: #03cfb4;
  border: none;
  padding: 0;
}
.modal p {
  font-style: normal;
}
.modal .actions {
  text-align: center;
  margin: 30px 0 10px 0;
  color: #333;
}
.modal .actions a {
  color: #333;
  padding: 8px;
  border: 1px solid #eee;
  border-radius: 4px;
  text-decoration: none;
  margin: 30px;
}

.modal.sale {
  background: crimson;
  color: white;
}
.modal.sale h1 {
  color: white;
}
.modal.sale .actions {
  color: white;
}
.modal.sale .actions a {
  color: white;
}
</style>
